language: node_js
node_js:
- 10.6.0
branches:
  only:
  - development
  - master
before_script:
- npm install -g @angular/cli

notifications:
  email:
    on_failure: change
    on_success: change

jobs:
  include:
  - stage: "build & test"
    script:
    - npm run ci
  - stage: "release to npm"
    if: branch = master
    script:
    - npm run build-prod
    before_deploy:
    - cd dist/processpuzzle-util-lib
    deploy:
      provider: npm
      email: zsolt.zsuffa@gmail.com
      api_key:
        secure: uYV5w393joJynUYMu8aHNso5sj0ri+oB43iFaxUhUWfEZFyNH5cKGzABP4jYkkJxSDID8P9ytW4JowLfr1F8xUDFlulpaz6WCKtSwL3zFB0xuxne7L9VCsUYfulvgg5cOfr6/CbqKor4d7GboIEVXcnORI66NLWyYXPlGikfusQOe83z8V1GCOwa1DPjAo/qJ4KEbwGDgiHrCLySzTDzsdIZ2UJX8TKEYPrZsFvhiSKbF2HbCpl3yXHquvTu1/cr+GoHIo3njc+pDUZL4y7kCqogIz9HWdRn25fGRyeZTDMbZONKKjrmFkEx3rqmKak/DKbbJkULIhFZgKytvS0CugS8ICY3/VuzigRNRtKlvjv1Fj5ioXtjA7TDxonevLmhZICT3BeWZEGSCbx7djZVq/tedgN9xYNjqQrQ2dfKye/NYi6xQFcFHH9lRVsLdk2XZNmroIG2rUc3WoI/ojj5GmkOlrt3LERkB92cnKdETFIsb7YXkUu9Zz9jQYRTk9wLIG/OBGmFAVNAT+gg4NnWndiNrDOeN8aIAiDA5UAIu1U0hM5STjDatlGKkPYuEyekNgdbIJqAZRnsgAtD2ZfuWsYSd2ykhewem20DEr5m6mHYfg8W1vfja83x2WQxP402tRYpURpyCPH4uhMtdsZbwzIl3k3fCBumMykWdAJtEF4=
      skip_cleanup: true
      on:
        branch: master
        tags: false
  - stage: "release to firebase"
    if: branch = master
    script:
    - npm run build-prod
    deploy:
      provider: firebase
      token:
        secure: FxyvD7O+cvHeSbk3Rdp1mFyeWan0AzziGVIXHz+JPw613qkFRypEq5DOOAy9psscuIokBvoQN9aQ7kRciiI7s8fmzAFMn3SxIyULuj7T//dAtc+Q5J6SWQp+RlJEwEXtfyJFPlf64GTBxnv3fg0YvtmzdkFpEIqhV8P1nOHRhjawDPH55OU6+uC2zgbwkchGM1cKlfvcZGjA0auRsl+nY3PMpFOLYYteNPohPdVD4MAtZkRko7UAu0O7p6m72ZYqheSe1UN4Z7IA7WbGsUYasg8lzVAGomNVDDpXNz9fQQXHSSy0mtwH2jjenLExqQEniOHQ9RSEi3iNyh+90egLDkRPIYSnNLz7+9O5tvLUl5bAR8dU/QuAmNbcqRH1Zv+ESwSeTp9eWE/2g+fOlnuZzH+LqpBSdUv15Eh4nIvPWP7iTiyMDLZfQHeekmJYtukvBMPssU8LesoviyAqviKyEilHzq2mgU1Xo+QhAm5jH281628nVnNQzD86FeVPrm3QDUlFSitDE+57mg9TnDTQcvtF9xsRGZZOHm+xMzZpSXdFuJHOiFocLer8e2qdqAqxjEd6h4BVMWJxGyPmDXDvtEDIFA3DHatrpX5uVdTP807ciijeWLKtAYUpEt5SrKgvxCC6YlRexM5DVDYXmyKBWRXiTLQDyb1lfTJ9Lj8Wmv8=
      skip_cleanup: true
      project: processpuzzle-util
      message: development build
      on:
        branch: master
        tags: false
