language: node_js
node_js:
  - "10.6.0"

branches:
  only:
    - development
    - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run ci

notifications:
  email:
    on_failure: change
    on_success: change
